# Generated by Django 5.2.14 on 2026-05-13 00:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('project', 'Project'), ('experience', 'Work Experience'), ('education', 'Education'), ('certification', 'Certification'), ('achievement', 'Achievement')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('raw', models.TextField()),
                ('context', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool'), ('database', 'Database'), ('cloud', 'Cloud'), ('other', 'Other')], max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('code', 'Code'), ('live', 'Live Demo'), ('demo_video', 'Demo Video'), ('screenshot', 'Screenshot')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='bank.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='skills',
            field=models.ManyToManyField(blank=True, to='bank.skill'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='bank.entry')),
            ],
        ),
    ]
